import type { MiraClass, MiraMentor, CommunityMember } from "@/types";

export const MENTORS: Record<string, MiraMentor> = {
  antoine: {
    id: "antoine",
    name: "Antoine Martin",
    headline: "Pitch investor · Fondateur SaaS B2B exitté",
    rating: 4.8,
    reviews: 47,
    classCount: 12,
  },
  marie: {
    id: "marie",
    name: "Marie Dupont",
    headline: "Lead Designer · ex Figma & Intercom",
    rating: 4.9,
    reviews: 38,
    classCount: 8,
  },
  david: {
    id: "david",
    name: "David Cohen",
    headline: "Growth B2B · ex Salesforce & HubSpot",
    rating: 4.7,
    reviews: 29,
    classCount: 6,
  },
};

export const CLASSES: MiraClass[] = [
  {
    slug: "pitcher-pour-lever-500k",
    title: "Pitcher pour lever 500k €",
    subtitle: "Construis ton deck investor + délivre ton pitch en 6 semaines",
    description:
      "Tu veux lever ta première seed mais tu n'as jamais pitché devant des investisseurs ?\n\nCette Mira Class t'amène, étape par étape, de \"j'ai une idée\" à \"je délivre un pitch de 7 minutes devant un jury investor simulé\". Avec Antoine, qui a lui-même levé 2,3M€ et accompagné 40+ founders.\n\nÀ la sortie : ton deck final (8-12 slides), ton pitch enregistré, et un feedback structuré d'Antoine sur les objections investisseur les plus courantes.",
    mentorId: "antoine",
    format: "Hybride",
    category: "Business",
    durationWeeks: 6,
    priceEur: 80,
    skills: ["Pitch investor", "Funding strategy"],
    primarySkill: "Pitch investor",
    cohortSize: 8,
    rating: 4.8,
    reviews: 47,
    modules: [
      { n: 1, title: "Construire le narratif investor", desc: "Storytelling + problème + solution + marché", dur: "3h" },
      { n: 2, title: "Design + délivery du deck", desc: "Deck visuel + pitch oral + gestion du stress", dur: "4h" },
      { n: 3, title: "Simulation pitch investor", desc: "Pitch live devant jury + feedback structuré", dur: "2h" },
    ],
    sessions: [
      {
        id: "s1",
        mode: "physical",
        location: "Barcelone, Espagne",
        dates: "5-26 juillet 2026",
        seats: 8,
        enrolled: 3,
      },
      {
        id: "s2",
        mode: "virtual",
        location: "Virtuel : sessions live + replays",
        dates: "Démarre 1er sept",
        seats: 10,
        enrolled: 0,
      },
    ],
  },
  {
    slug: "ui-design-saas-b2b",
    title: "UI Design pour SaaS B2B",
    subtitle: "Maîtrise les patterns de l'interface SaaS moderne en 4 semaines",
    description:
      "Le B2B SaaS a ses propres patterns : tables de données, filtres, états vides, onboarding progressif. Cette class te donne les outils pour les maîtriser avec Figma.\n\nMarie a designé des interfaces chez Figma et Intercom. Elle t'apporte les patterns éprouvés des meilleures équipes product.",
    mentorId: "marie",
    format: "Virtuel",
    category: "Design",
    durationWeeks: 4,
    priceEur: 60,
    skills: ["UI Design", "Design System"],
    primarySkill: "UI Design",
    cohortSize: 10,
    rating: 4.9,
    reviews: 38,
    modules: [
      { n: 1, title: "Patterns de données", desc: "Tables, filtres, pagination, états vides", dur: "3h" },
      { n: 2, title: "Design system SaaS", desc: "Composants réutilisables + tokens", dur: "4h" },
    ],
    sessions: [
      {
        id: "s3",
        mode: "virtual",
        location: "Virtuel : live hebdo + replays",
        dates: "Démarre 15 juin",
        seats: 10,
        enrolled: 6,
      },
    ],
  },
  {
    slug: "growth-b2b-go-to-market",
    title: "Growth B2B go-to-market",
    subtitle: "Lance ton SaaS B2B en 8 semaines avec une vraie stratégie GTM",
    description:
      "De 0 à tes premiers 10 clients payants. David a fait ça plusieurs fois chez Salesforce et en startup. Il t'apporte le playbook complet : ICP, messaging, outbound, inbound, referral.",
    mentorId: "david",
    format: "Virtuel",
    category: "Business",
    durationWeeks: 8,
    priceEur: 49,
    skills: ["Growth", "B2B", "Go-to-market"],
    primarySkill: "Growth",
    cohortSize: 12,
    rating: 4.7,
    reviews: 29,
    modules: [
      { n: 1, title: "ICP + messaging", desc: "Définir l'Ideal Customer Profile + pitch 1 phrase", dur: "2h" },
      { n: 2, title: "Outbound playbook", desc: "Cold email + LinkedIn + suivi", dur: "3h" },
      { n: 3, title: "Inbound + referral", desc: "SEO, contenu, partenariats", dur: "3h" },
    ],
    sessions: [
      {
        id: "s4",
        mode: "virtual",
        location: "Virtuel : live bi-mensuel",
        dates: "Démarre 1er juillet",
        seats: 12,
        enrolled: 2,
      },
    ],
  },
];

export const COMMUNITY_MEMBERS: CommunityMember[] = [
  {
    id: "anna",
    name: "Anna Lopez",
    city: "Lisbonne, PT",
    flag: "🇵🇹",
    since: "nomade depuis 2021",
    target: ["Pitch investor", "Funding strategy"],
    validated: [],
    completed: false,
    lat: 38.7,
    lng: -9.1,
  },
  {
    id: "marco",
    name: "Marco Silva",
    city: "São Paulo, BR",
    flag: "🇧🇷",
    since: "nomade depuis 2022",
    target: ["UI Design", "Design System"],
    validated: ["Figma"],
    completed: false,
    lat: -23.5,
    lng: -46.6,
  },
  {
    id: "lea",
    name: "Léa Bauer",
    city: "Berlin, DE",
    flag: "🇩🇪",
    since: "nomade depuis 2023",
    target: [],
    validated: [],
    completed: false,
    lat: 52.5,
    lng: 13.4,
  },
  {
    id: "tom",
    name: "Tom Evans",
    city: "Londres, GB",
    flag: "🇬🇧",
    since: "nomade depuis 2020",
    target: ["Growth", "B2B"],
    validated: ["Growth", "B2B"],
    completed: true,
    lat: 51.5,
    lng: -0.1,
  },
  {
    id: "clara",
    name: "Clara Kovač",
    city: "Prague, CZ",
    flag: "🇨🇿",
    since: "nomade depuis 2024",
    target: ["Pitch investor"],
    validated: [],
    completed: false,
    lat: 50.1,
    lng: 14.4,
  },
];

export function getClassBySlug(slug: string): MiraClass | undefined {
  return CLASSES.find((c) => c.slug === slug);
}
